// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnIENc6MI8fhVMGJiBsYQSCtrZm1t8HKM',
    appId: '1:565252686140:web:f3ef2da6772222ee841e39',
    messagingSenderId: '565252686140',
    projectId: 'new-folder-929c7',
    authDomain: 'new-folder-929c7.firebaseapp.com',
    databaseURL: 'https://new-folder-929c7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'new-folder-929c7.appspot.com',
    measurementId: 'G-WFL6Z71FB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrSrC4WbIbXd2-oxodjcViaRgKwX2uJGk',
    appId: '1:565252686140:android:58db6b796ea1e21a841e39',
    messagingSenderId: '565252686140',
    projectId: 'new-folder-929c7',
    databaseURL: 'https://new-folder-929c7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'new-folder-929c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw83soTwv6XSJnnFM84usrUZ7rNDcj3cU',
    appId: '1:565252686140:ios:5670ff727a0d0083841e39',
    messagingSenderId: '565252686140',
    projectId: 'new-folder-929c7',
    databaseURL: 'https://new-folder-929c7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'new-folder-929c7.appspot.com',
    iosClientId: '565252686140-9jlh3puu5aksoamnvs85l6fal140une3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw83soTwv6XSJnnFM84usrUZ7rNDcj3cU',
    appId: '1:565252686140:ios:5670ff727a0d0083841e39',
    messagingSenderId: '565252686140',
    projectId: 'new-folder-929c7',
    databaseURL: 'https://new-folder-929c7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'new-folder-929c7.appspot.com',
    iosClientId: '565252686140-9jlh3puu5aksoamnvs85l6fal140une3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
